import { spawn } from "node:child_process";
import { createServer } from "node:net";
import { mkdtemp, readdir, mkdir, rm, writeFile, readFile, stat, access } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";

const root = process.cwd();
const verify = process.argv.includes("--verify");

function resolveRoot(...parts) {
  return path.resolve(root, ...parts);
}

async function exec(cmd, args, options = {}) {
  await new Promise((resolve, reject) => {
    const child = spawn(cmd, args, {
      cwd: root,
      shell: false,
      stdio: options.quiet ? "pipe" : "inherit",
      windowsHide: true,
    });
    let output = "";
    if (child.stdout) child.stdout.on("data", (chunk) => (output += chunk));
    if (child.stderr) child.stderr.on("data", (chunk) => (output += chunk));
    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) resolve(output);
      else reject(new Error(`${cmd} ${args.join(" ")} exited with ${code}\n${output}`));
    });
  });
}

async function waitForHttp(url, { timeoutMs = 30000 } = {}) {
  const started = Date.now();
  let lastError = "";
  while (Date.now() - started < timeoutMs) {
    try {
      const response = await fetch(url);
      if (response.ok) return;
      lastError = `${response.status} ${response.statusText}`;
    } catch (error) {
      lastError = error.message;
    }
    await delay(500);
  }
  throw new Error(`timed out waiting for ${url}: ${lastError}`);
}

async function requestJSON(url, options = {}) {
  const headers = new Headers(options.headers || {});
  headers.set("accept", "application/json");
  let body = options.body;
  if (body !== undefined && typeof body !== "string") {
    headers.set("content-type", "application/json");
    body = JSON.stringify(body);
  }
  const response = await fetch(url, { ...options, headers, body });
  const text = await response.text();
  let data = text;
  if (text) {
    try {
      data = JSON.parse(text);
    } catch {
      data = text;
    }
  }
  if (!response.ok) {
    const message = data && data.error ? data.error : `${response.status} ${response.statusText}`;
    throw new Error(message);
  }
  return data;
}

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function loadScenarios(config) {
  const dir = resolveRoot(config.scenariosDir);
  const names = (await readdir(dir)).filter((name) => name.endsWith(".mjs")).sort();
  const scenarios = [];
  for (const name of names) {
    const module = await import(pathToFileURL(path.join(dir, name)).href + `?v=${Date.now()}`);
    scenarios.push(module.default);
  }
  return scenarios.sort((left, right) => {
    const order = (left.order ?? 1000) - (right.order ?? 1000);
    if (order !== 0) return order;
    return left.id.localeCompare(right.id);
  });
}

function renderGuide(config, scenarios) {
  const guidePath = resolveRoot(config.guidePath);
  const guideDir = path.dirname(guidePath);
  const lines = [
    "# windforce-lite Web UI User Guide",
    "",
    "<!-- Generated by `node tools/ui-guide/capture.mjs`. Edit `docs/ui-scenarios/*.mjs` instead. -->",
    "",
    "This guide is generated from executable UI scenarios. Screenshots are captured from the local windforce-lite devstack.",
    "",
  ];
  for (const scenario of scenarios) {
    const screenshot = path.relative(guideDir, resolveRoot(scenario.screenshot)).replaceAll("\\", "/");
    lines.push(`## ${scenario.title}`, "");
    lines.push(scenario.description, "");
    lines.push(`![${scenario.title}](${screenshot})`, "");
    if (Array.isArray(scenario.guide) && scenario.guide.length > 0) {
      scenario.guide.forEach((step, index) => lines.push(`${index + 1}. ${step}`));
      lines.push("");
    }
  }
  return lines.join("\n");
}

async function writeGuide(config, scenarios) {
  const guidePath = resolveRoot(config.guidePath);
  const guideDir = path.dirname(guidePath);
  await mkdir(guideDir, { recursive: true });
  await writeFile(guidePath, renderGuide(config, scenarios), "utf8");
}

async function verifyGuide(config, scenarios) {
  const guidePath = resolveRoot(config.guidePath);
  const expected = renderGuide(config, scenarios);
  const actual = await readFile(guidePath, "utf8");
  if (actual !== expected) {
    throw new Error(`${config.guidePath} is stale; run make ui-guide`);
  }
  for (const scenario of scenarios) {
    const info = await stat(resolveRoot(scenario.screenshot));
    if (!info.isFile() || info.size === 0) {
      throw new Error(`${scenario.screenshot} is missing or empty; run make ui-guide`);
    }
  }
}

async function createPlaywrightBrowser(config) {
  let playwright;
  try {
    playwright = await import("playwright");
  } catch {
    return null;
  }
  let browser;
  for (const channel of ["chrome", "msedge"]) {
    try {
      browser = await playwright.chromium.launch({ channel, headless: true });
      break;
    } catch {
      // Try the next installed browser channel.
    }
  }
  if (!browser) {
    try {
      browser = await playwright.chromium.launch({ headless: true });
    } catch {
      return null;
    }
  }
  return {
    async newPage() {
      const context = await browser.newContext({ viewport: config.viewport });
      const page = await context.newPage();
      const errors = [];
      page.on("pageerror", (error) => errors.push(error.message));
      page.on("console", (message) => {
        if (message.type() === "error" && !message.text().includes("favicon")) {
          errors.push(message.text());
        }
      });
      return {
        async goto() {
          await page.goto(config.baseUrl, { waitUntil: "networkidle" });
        },
        async click(selector) {
          await page.locator(selector).first().click();
        },
        async clickText(text) {
          await page.getByRole("button", { name: text }).click();
        },
        async fill(selector, value) {
          await page.locator(selector).fill(value);
        },
        async waitForSelector(selector) {
          await page.waitForSelector(selector, { state: "visible" });
        },
        async waitForText(selector, text) {
          await page.waitForFunction(
            ([sel, expected]) => document.querySelector(sel)?.textContent.includes(expected),
            [selector, text],
          );
        },
        async evaluate(fn) {
          return page.evaluate(fn);
        },
        async screenshot(file) {
          if (errors.length > 0) throw new Error(`browser errors:\n${errors.join("\n")}`);
          await page.screenshot({ path: file, fullPage: false });
        },
        async close() {
          await context.close();
        },
      };
    },
    async close() {
      await browser.close();
    },
  };
}

async function createCdpBrowser(config) {
  const chromePath = await findChrome();
  const port = await freePort();
  const userDataDir = await mkdtemp(path.join(tmpdir(), "windforce-lite-ui-guide-"));
  const child = spawn(chromePath, [
    "--headless=new",
    `--remote-debugging-port=${port}`,
    `--user-data-dir=${userDataDir}`,
    "--disable-gpu",
    "--no-first-run",
    "--no-default-browser-check",
    `--window-size=${config.viewport.width},${config.viewport.height}`,
    "about:blank",
  ], { stdio: "ignore", windowsHide: true });

  const wsURL = await waitForCdp(port);
  const ws = new WebSocket(wsURL);
  await new Promise((resolve, reject) => {
    ws.addEventListener("open", resolve, { once: true });
    ws.addEventListener("error", reject, { once: true });
  });
  let id = 0;
  const pending = new Map();
  ws.addEventListener("message", (event) => {
    const message = JSON.parse(event.data);
    if (!message.id) return;
    const item = pending.get(message.id);
    if (!item) return;
    pending.delete(message.id);
    if (message.error) item.reject(new Error(message.error.message));
    else item.resolve(message.result);
  });
  function send(method, params = {}, sessionId = undefined) {
    const message = { id: ++id, method, params };
    if (sessionId) message.sessionId = sessionId;
    ws.send(JSON.stringify(message));
    return new Promise((resolve, reject) => pending.set(message.id, { resolve, reject }));
  }

  return {
    async newPage() {
      const target = await send("Target.createTarget", { url: "about:blank" });
      const attached = await send("Target.attachToTarget", { targetId: target.targetId, flatten: true });
      const sessionId = attached.sessionId;
      const page = new CdpPage(config, send, sessionId);
      await page.initialize();
      return page;
    },
    async close() {
      ws.close();
      await stopProcess(child);
      await removeTempDir(userDataDir);
    },
  };
}

async function stopProcess(child) {
  if (child.exitCode !== null) return;
  child.kill();
  await new Promise((resolve) => {
    child.once("exit", resolve);
    setTimeout(resolve, 2000);
  });
}

async function removeTempDir(dir) {
  for (let attempt = 0; attempt < 5; attempt += 1) {
    try {
      await rm(dir, { recursive: true, force: true });
      return;
    } catch (error) {
      if (!["EBUSY", "EPERM", "ENOTEMPTY"].includes(error.code)) throw error;
      await sleep(250 * (attempt + 1));
    }
  }
}

class CdpPage {
  constructor(config, send, sessionId) {
    this.config = config;
    this.send = send;
    this.sessionId = sessionId;
  }

  async initialize() {
    await this.send("Page.enable", {}, this.sessionId);
    await this.send("Runtime.enable", {}, this.sessionId);
    await this.send("Emulation.setDeviceMetricsOverride", {
      width: this.config.viewport.width,
      height: this.config.viewport.height,
      deviceScaleFactor: 1,
      mobile: false,
    }, this.sessionId);
  }

  async goto() {
    await this.send("Page.navigate", { url: this.config.baseUrl }, this.sessionId);
    await this.waitForFunction(() => document.readyState === "complete");
    await delay(500);
  }

  async click(selector) {
    await this.evaluate((sel) => {
      const el = document.querySelector(sel);
      if (!el) throw new Error(`selector not found: ${sel}`);
      el.click();
    }, selector);
    await delay(200);
  }

  async clickText(text) {
    await this.evaluate((label) => {
      const candidates = Array.from(document.querySelectorAll("button, [role='button'], a"));
      const el = candidates.find((item) => item.textContent.trim() === label);
      if (!el) throw new Error(`button not found: ${label}`);
      el.click();
    }, text);
    await delay(200);
  }

  async fill(selector, value) {
    await this.evaluate((args) => {
      const el = document.querySelector(args.selector);
      if (!el) throw new Error(`selector not found: ${args.selector}`);
      el.value = args.value;
      el.dispatchEvent(new Event("input", { bubbles: true }));
      el.dispatchEvent(new Event("change", { bubbles: true }));
    }, { selector, value });
  }

  async waitForSelector(selector) {
    await this.waitForFunction((sel) => {
      const el = document.querySelector(sel);
      if (!el) return false;
      const rect = el.getBoundingClientRect();
      return rect.width > 0 && rect.height > 0;
    }, selector);
  }

  async waitForText(selector, text) {
    await this.waitForFunction((args) => document.querySelector(args.selector)?.textContent.includes(args.text), {
      selector,
      text,
    });
  }

  async waitForFunction(fn, arg = undefined, timeoutMs = 30000) {
    const started = Date.now();
    let lastError = "";
    while (Date.now() - started < timeoutMs) {
      try {
        if (await this.evaluate(fn, arg)) return;
      } catch (error) {
        lastError = error.message;
      }
      await delay(250);
    }
    throw new Error(`timed out waiting for function: ${lastError}`);
  }

  async evaluate(fn, arg = undefined) {
    const expression = `(${fn.toString()})(${JSON.stringify(arg)})`;
    const result = await this.send("Runtime.evaluate", {
      expression,
      awaitPromise: true,
      returnByValue: true,
      userGesture: true,
    }, this.sessionId);
    if (result.exceptionDetails) {
      throw new Error(result.exceptionDetails.exception?.description || "Runtime.evaluate failed");
    }
    return result.result.value;
  }

  async screenshot(file) {
    const result = await this.send("Page.captureScreenshot", { format: "png", fromSurface: true }, this.sessionId);
    await writeFile(file, Buffer.from(result.data, "base64"));
  }

  async close() {
    // The browser process is short-lived for this runner, so target cleanup is unnecessary.
  }
}

async function findChrome() {
  const candidates = [
    process.env.CHROME_PATH,
    process.env.BROWSER_PATH,
    "C:/Program Files/Google/Chrome/Application/chrome.exe",
    "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
    "C:/Program Files/Microsoft/Edge/Application/msedge.exe",
    "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",
  ].filter(Boolean);
  for (const candidate of candidates) {
    try {
      await access(candidate);
      return candidate;
    } catch {
      // Try the next path.
    }
  }
  throw new Error("Chrome or Edge not found. Set CHROME_PATH to a Chromium-compatible browser.");
}

async function freePort() {
  const server = createServer();
  await new Promise((resolve, reject) => {
    server.listen(0, "127.0.0.1", resolve);
    server.on("error", reject);
  });
  const port = server.address().port;
  await new Promise((resolve) => server.close(resolve));
  return port;
}

async function waitForCdp(port) {
  const url = `http://127.0.0.1:${port}/json/version`;
  const started = Date.now();
  while (Date.now() - started < 10000) {
    try {
      const response = await fetch(url);
      if (response.ok) {
        const payload = await response.json();
        if (payload.webSocketDebuggerUrl) return payload.webSocketDebuggerUrl;
      }
    } catch {
      // Keep polling until Chrome starts.
    }
    await delay(200);
  }
  throw new Error("timed out waiting for Chrome DevTools Protocol");
}

async function main() {
  const configModule = await import(pathToFileURL(resolveRoot("ui-guide.config.mjs")).href + `?v=${Date.now()}`);
  const config = configModule.default;
  const scenarios = await loadScenarios(config);
  const verifyScreenshotsDir = verify ? await mkdtemp(path.join(tmpdir(), "windforce-lite-ui-guide-verify-")) : "";
  if (!verify) await mkdir(resolveRoot(config.screenshotsDir), { recursive: true });

  const api = (apiPath, options) => requestJSON(config.apiBaseUrl + apiPath, options);
  if (config.start) await config.start({ exec, waitForHttp });
  if (config.seed) await config.seed({ api, exec, waitForHttp });

  const browser = (await createPlaywrightBrowser(config)) || (await createCdpBrowser(config));
  try {
    for (const scenario of scenarios) {
      const page = await browser.newPage();
      try {
        const capture = async () => {
          const file = verify ? path.join(verifyScreenshotsDir, `${scenario.id}.png`) : resolveRoot(scenario.screenshot);
          await mkdir(path.dirname(file), { recursive: true });
          await stabilizePage(page);
          await page.screenshot(file);
        };
        await scenario.run({ page, capture, api, config });
      } finally {
        await page.close();
      }
    }
  } finally {
    await browser.close();
  }

  if (verify) {
    await verifyGuide(config, scenarios);
    await rm(verifyScreenshotsDir, { recursive: true, force: true });
    console.log("UI guide verified.");
  } else {
    await writeGuide(config, scenarios);
    console.log("UI guide generated.");
  }
}

main().catch((error) => {
  console.error(error.stack || error.message);
  process.exit(1);
});

async function stabilizePage(page) {
  await page.evaluate(() => {
    let style = document.querySelector("#ui-guide-stability-style");
    if (!style) {
      style = document.createElement("style");
      style.id = "ui-guide-stability-style";
      document.head.appendChild(style);
    }
    style.textContent = `
      *, *::before, *::after {
        animation: none !important;
        caret-color: transparent !important;
        transition: none !important;
      }
    `;
    if (document.activeElement instanceof HTMLElement) {
      document.activeElement.blur();
    }
    window.scrollTo(0, 0);
  });
  await delay(100);
}
