"use client";

import { useCallback, useEffect, useMemo, useState, type ComponentProps } from "react";
import type { AppDetail, AppHistoryItem, AppSummary } from "@/entities/app";
import type { GitSource } from "@/entities/git-source";
import { SettingsDialog } from "@/features/control-plane-settings/ui/SettingsDialog";
import { DeploySourceDialog } from "@/features/deploy-source/ui/DeploySourceDialog";
import { SourceRegistrationForm } from "@/features/source-registration/ui/SourceRegistrationForm";
import { Sidebar } from "@/widgets/sidebar";
import { Topbar } from "@/widgets/topbar";
import { WindforceApi } from "@/shared/api/client";
import type { ApiSettings, VariableRow, WorkerTagsResponse } from "@/shared/api/types";
import { shortID } from "@/shared/lib/format";
import { AuditSection, DeploymentsSection, ReleasesSection, SourcesSection } from "./DeploymentPanels";
import type { ConsoleSection, DetailTab, Notice } from "./types";

const defaultSettings: ApiSettings = {
  workspace: "default",
  token: "",
  actor: "",
};

const sectionCopy: Record<ConsoleSection, { title: string; subtitle: string }> = {
  deployments: {
    title: "Deployment Console",
    subtitle: "Select a deployable FCode, inspect the current contract, and publish a guarded release.",
  },
  sources: {
    title: "Source Registry",
    subtitle: "Manage Git repositories, credentials, branch, and manifest validation state.",
  },
  releases: {
    title: "Release Contracts",
    subtitle: "Review the worker-visible app contract generated by the latest deployment.",
  },
  audit: {
    title: "Deployment Audit",
    subtitle: "Track who deployed which commit and the source snapshot used for that release.",
  },
};

export function DeploymentsView() {
  const [settings, setSettings] = useState<ApiSettings>(defaultSettings);
  const [sources, setSources] = useState<GitSource[]>([]);
  const [apps, setApps] = useState<AppSummary[]>([]);
  const [variables, setVariables] = useState<VariableRow[]>([]);
  const [workerTags, setWorkerTags] = useState<WorkerTagsResponse>({});
  const [selectedSourceID, setSelectedSourceID] = useState<number | null>(null);
  const [selectedAppKey, setSelectedAppKey] = useState("");
  const [appDetail, setAppDetail] = useState<AppDetail | null>(null);
  const [history, setHistory] = useState<AppHistoryItem[]>([]);
  const [sourceFiles, setSourceFiles] = useState<Record<string, string>>({});
  const [deploySource, setDeploySource] = useState<GitSource | null>(null);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState<Notice>({ tone: "info", text: "" });
  const [deployError, setDeployError] = useState("");
  const [activeSection, setActiveSection] = useState<ConsoleSection>("deployments");
  const [detailTab, setDetailTab] = useState<DetailTab>("contract");
  const [search, setSearch] = useState("");
  const [registrationOpen, setRegistrationOpen] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);

  useEffect(() => {
    const saved = globalThis.localStorage;
    setSettings({
      workspace: saved.getItem("wf.workspace") || "default",
      token: saved.getItem("wf.token") || "",
      actor: saved.getItem("wf.actor") || "",
    });
  }, []);

  useEffect(() => {
    localStorage.setItem("wf.workspace", settings.workspace);
    localStorage.setItem("wf.token", settings.token);
    localStorage.setItem("wf.actor", settings.actor);
  }, [settings]);

  const api = useMemo(() => new WindforceApi(settings), [settings]);
  const selectedSource = sources.find((source) => source.id === selectedSourceID) || null;
  const selectedApp = selectedSource
    ? apps.find((app) => app.git_source_id === selectedSource.id) || null
    : apps.find((app) => app.app_key === selectedAppKey) || null;
  const liveWorkers = (workerTags.tags || []).reduce((total, tag) => total + Number(tag.live_workers || 0), 0);
  const credentialCount = variables.filter((item) => item.path?.startsWith("git/")).length;

  const refresh = useCallback(async () => {
    setBusy(true);
    setNotice({ tone: "info", text: "Refreshing deployment state..." });
    try {
      const [nextVariables, nextSources, nextApps, nextTags] = await Promise.all([
        api.variables(),
        api.gitSources(),
        api.apps(),
        api.workerTags(),
      ]);
      setVariables(nextVariables);
      setSources(nextSources);
      setApps(nextApps.apps || []);
      setWorkerTags(nextTags);
      setSelectedSourceID((current) => {
        if (current && nextSources.some((source) => source.id === current)) return current;
        return nextSources[0]?.id || null;
      });
      setSelectedAppKey((current) => {
        if (current && nextApps.apps?.some((app) => app.app_key === current)) return current;
        return nextApps.apps?.[0]?.app_key || "";
      });
      setNotice({ tone: "ok", text: "Deployment state refreshed." });
    } catch (error) {
      setNotice({ tone: "error", text: error instanceof Error ? error.message : String(error) });
    } finally {
      setBusy(false);
    }
  }, [api]);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  useEffect(() => {
    const appKey = selectedApp?.app_key || (selectedSource ? "" : selectedAppKey);
    if (!appKey) {
      setAppDetail(null);
      setHistory([]);
      setSourceFiles({});
      return;
    }
    let canceled = false;
    async function loadApp() {
      try {
        const [detail, nextHistory, source] = await Promise.all([
          api.app(appKey),
          api.appHistory(appKey),
          api.appSource(appKey).catch(() => ({ files: {} })),
        ]);
        if (canceled) return;
        setAppDetail(detail);
        setHistory(nextHistory);
        setSourceFiles(source.files || {});
      } catch (error) {
        if (!canceled) setNotice({ tone: "error", text: error instanceof Error ? error.message : String(error) });
      }
    }
    void loadApp();
    return () => {
      canceled = true;
    };
  }, [api, selectedApp?.app_key, selectedAppKey]);

  async function run(label: string, action: () => Promise<string | void>) {
    setBusy(true);
    setNotice({ tone: "info", text: label });
    try {
      const success = await action();
      setNotice({ tone: "ok", text: success || "Done" });
    } catch (error) {
      setNotice({ tone: "error", text: error instanceof Error ? error.message : String(error) });
    } finally {
      setBusy(false);
    }
  }

  function navigate(section: ConsoleSection) {
    setActiveSection(section);
    if (section === "sources") setDetailTab("source");
    if (section === "releases") setDetailTab("contract");
    if (section === "audit") setDetailTab("history");
  }

  async function deploy(message: string) {
    if (!deploySource) return;
    setDeployError("");
    await run(`Deploying ${deploySource.name}`, async () => {
      const result = await api.deployGitSource(deploySource.id, message ? { confirm: true, message } : { confirm: true });
      setDeploySource(null);
      setSelectedSourceID(deploySource.id);
      setSelectedAppKey(result.app);
      setDetailTab("history");
      await refresh();
      return `Deployed ${result.app} at ${shortID(result.commit, 12)}`;
    });
  }

  const removeSource = (source: GitSource) => run(`Removing ${source.name}`, async () => {
    const confirmed = globalThis.confirm(`Remove source ${source.name}? This does not remove deployed history.`);
    if (!confirmed) return "Remove canceled.";
    await api.deleteGitSource(source.id);
    await refresh();
    return `Removed ${source.name}.`;
  });

  return (
    <main className="appShell">
      <Sidebar
        active={activeSection}
        sourceCount={sources.length}
        appCount={apps.length}
        credentialCount={credentialCount}
        liveWorkers={liveWorkers}
        onNavigate={navigate}
        onSettings={() => setSettingsOpen(true)}
      />
      <section className="mainArea">
        <Topbar
          title={sectionCopy[activeSection].title}
          subtitle={sectionCopy[activeSection].subtitle}
          settings={settings}
          busy={busy}
          onRefresh={refresh}
          onRegister={() => setRegistrationOpen(true)}
          onSettings={() => setSettingsOpen(true)}
        />

        <div className="content">
          {notice.text ? <div id="notice" className={`notice ${notice.tone}`}>{notice.text}</div> : null}
          <ActiveSection
            section={activeSection}
            sources={sources}
            apps={apps}
            selectedSourceID={selectedSourceID}
            selectedSource={selectedSource}
            selectedApp={selectedApp}
            detail={appDetail}
            history={history}
            sourceFiles={sourceFiles}
            search={search}
            activeTab={detailTab}
            actor={settings.actor}
            liveWorkers={liveWorkers}
            onSearch={setSearch}
            onSelectSource={setSelectedSourceID}
            onRegister={() => setRegistrationOpen(true)}
            onDeploy={setDeploySource}
            onRemove={removeSource}
            onTabChange={setDetailTab}
            onSettings={() => setSettingsOpen(true)}
          />
        </div>
      </section>

      {registrationOpen ? (
        <div id="registerSourceDialog" className="modalBackdrop" role="presentation">
          <section className="dialog wideDialog" aria-label="Register FCode source">
            <SourceRegistrationForm
              busy={busy}
              onCancel={() => setRegistrationOpen(false)}
              onRegister={(payload) => run("Registering source", async () => {
                const created = await api.registerGitSource(payload);
                setSelectedSourceID(created.id);
                setRegistrationOpen(false);
                await refresh();
                return `Registered ${created.name}.`;
              })}
              onProbe={(payload) => run("Probing repository", async () => {
                const result = await api.probeGitSource(payload);
                return result.reachable ? "Repository reachable for deployment." : result.error || "Repository is not reachable.";
              })}
              onCreateSample={() => run("Creating sample", async () => {
                await api.sample("echo");
                setRegistrationOpen(false);
                await refresh();
                return "Created sample source.";
              })}
            />
          </section>
        </div>
      ) : null}

      <SettingsDialog open={settingsOpen} settings={settings} onSave={setSettings} onClose={() => setSettingsOpen(false)} />

      <DeploySourceDialog
        source={deploySource}
        actor={settings.actor}
        busy={busy}
        error={deployError}
        onClose={() => {
          setDeployError("");
          setDeploySource(null);
        }}
        onDeploy={deploy}
        onOpenSettings={() => setSettingsOpen(true)}
      />
    </main>
  );
}

type ActiveSectionProps = ComponentProps<typeof DeploymentsSection> & {
  section: ConsoleSection;
};

function ActiveSection({ section, ...props }: ActiveSectionProps) {
  if (section === "sources") return <SourcesSection {...props} />;
  if (section === "releases") return <ReleasesSection {...props} />;
  if (section === "audit") return <AuditSection {...props} />;
  return <DeploymentsSection {...props} />;
}
