"use client";

import { useCallback, useEffect, useMemo, useState, type ComponentProps } from "react";
import type { AppDetail, AppHistoryItem, AppSummary, DeploymentRequest } from "@/entities/app";
import type { GitSource } from "@/entities/git-source";
import { SettingsPage } from "@/features/control-plane-settings/ui/SettingsPage";
import { RequestDeploymentDialog, ReviewDeploymentRequestDialog } from "@/features/deployment-request/ui/DeploymentRequestDialogs";
import { SourceRegistrationForm } from "@/features/source-registration/ui/SourceRegistrationForm";
import { Sidebar } from "@/widgets/sidebar";
import { Topbar } from "@/widgets/topbar";
import { WindforceApi } from "@/shared/api/client";
import type { ApiSettings, VariableRow, WorkerTagsResponse } from "@/shared/api/types";
import { shortID } from "@/shared/lib/format";
import { AuditSection, DeploymentsSection, ReleasesSection, SourcesSection } from "./DeploymentPanels";
import { DeploymentRequestDetailSection, FCodeDetailSection } from "./DeploymentDetailPages";
import type { ConsoleSection, DetailPage, DetailTab, Notice } from "./types";

const defaultSettings: ApiSettings = {
  workspace: "default",
  token: "",
  actor: "",
};

const sectionCopy: Record<ConsoleSection, { title: string; subtitle: string }> = {
  deployments: {
    title: "Deployment Console",
    subtitle: "Review deployment requests, inspect pinned commits, and publish guarded releases.",
  },
  sources: {
    title: "Source Registry",
    subtitle: "Manage Git repositories, credentials, branch, and manifest validation state.",
  },
  releases: {
    title: "Release Contracts",
    subtitle: "Review the worker-visible app contract generated by the latest deployment.",
  },
  audit: {
    title: "Deployment Audit",
    subtitle: "Track who deployed which commit and the source snapshot used for that release.",
  },
  settings: {
    title: "Control Plane Settings",
    subtitle: "Set the workspace, API token, and actor used by deployment operations.",
  },
};

export function DeploymentsView() {
  const [settings, setSettings] = useState<ApiSettings>(defaultSettings);
  const [sources, setSources] = useState<GitSource[]>([]);
  const [apps, setApps] = useState<AppSummary[]>([]);
  const [deploymentRequests, setDeploymentRequests] = useState<DeploymentRequest[]>([]);
  const [variables, setVariables] = useState<VariableRow[]>([]);
  const [workerTags, setWorkerTags] = useState<WorkerTagsResponse>({});
  const [selectedSourceID, setSelectedSourceID] = useState<number | null>(null);
  const [selectedAppKey, setSelectedAppKey] = useState("");
  const [appDetail, setAppDetail] = useState<AppDetail | null>(null);
  const [history, setHistory] = useState<AppHistoryItem[]>([]);
  const [sourceFiles, setSourceFiles] = useState<Record<string, string>>({});
  const [requestSource, setRequestSource] = useState<GitSource | null>(null);
  const [reviewRequest, setReviewRequest] = useState<DeploymentRequest | null>(null);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState<Notice>({ tone: "info", text: "" });
  const [deployError, setDeployError] = useState("");
  const [activeSection, setActiveSection] = useState<ConsoleSection>("deployments");
  const [detailPage, setDetailPage] = useState<DetailPage | null>(null);
  const [detailTab, setDetailTab] = useState<DetailTab>("contract");
  const [search, setSearch] = useState("");
  const [registrationOpen, setRegistrationOpen] = useState(false);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);

  useEffect(() => {
    const saved = globalThis.localStorage;
    setSettings({
      workspace: saved.getItem("wf.workspace") || "default",
      token: saved.getItem("wf.token") || "",
      actor: saved.getItem("wf.actor") || "",
    });
    setSidebarCollapsed(saved.getItem("wf.sidebarCollapsed") === "true");
  }, []);

  useEffect(() => {
    function syncDetailFromURL() {
      setDetailPage(readDetailPageFromLocation());
    }
    syncDetailFromURL();
    window.addEventListener("popstate", syncDetailFromURL);
    return () => window.removeEventListener("popstate", syncDetailFromURL);
  }, []);

  useEffect(() => {
    localStorage.setItem("wf.workspace", settings.workspace);
    localStorage.setItem("wf.token", settings.token);
    localStorage.setItem("wf.actor", settings.actor);
  }, [settings]);

  useEffect(() => {
    localStorage.setItem("wf.sidebarCollapsed", String(sidebarCollapsed));
  }, [sidebarCollapsed]);

  useEffect(() => {
    if (!notice.text || notice.tone === "error") return;
    const timer = window.setTimeout(() => setNotice((current) => current.text === notice.text ? { tone: "info", text: "" } : current), 2400);
    return () => window.clearTimeout(timer);
  }, [notice]);

  const api = useMemo(() => new WindforceApi(settings), [settings]);
  const selectedSource = sources.find((source) => source.id === selectedSourceID) || null;
  const selectedApp = selectedSource
    ? apps.find((app) => app.git_source_id === selectedSource.id) || null
    : apps.find((app) => app.app_key === selectedAppKey) || null;
  const liveWorkers = (workerTags.tags || []).reduce((total, tag) => total + Number(tag.live_workers || 0), 0);
  const credentialCount = variables.filter((item) => item.path?.startsWith("git/")).length;

  const refresh = useCallback(async () => {
    setBusy(true);
    setNotice({ tone: "info", text: "Refreshing deployment state..." });
    try {
      const [nextVariables, nextSources, nextApps, nextTags, nextRequests] = await Promise.all([
        api.variables(),
        api.gitSources(),
        api.apps(),
        api.workerTags(),
        api.deploymentRequests(),
      ]);
      setVariables(nextVariables);
      setSources(nextSources);
      setApps(nextApps.apps || []);
      setWorkerTags(nextTags);
      setDeploymentRequests(nextRequests.requests || []);
      setSelectedSourceID((current) => {
        if (current && nextSources.some((source) => source.id === current)) return current;
        return nextSources[0]?.id || null;
      });
      setSelectedAppKey((current) => {
        if (current && nextApps.apps?.some((app) => app.app_key === current)) return current;
        return nextApps.apps?.[0]?.app_key || "";
      });
      setNotice({ tone: "ok", text: "Deployment state refreshed." });
    } catch (error) {
      setNotice({ tone: "error", text: error instanceof Error ? error.message : String(error) });
    } finally {
      setBusy(false);
    }
  }, [api]);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  useEffect(() => {
    if (detailPage?.kind === "fcode" && sources.some((source) => source.id === detailPage.sourceID)) {
      setSelectedSourceID(detailPage.sourceID);
    }
    if (detailPage?.kind === "request") {
      const request = deploymentRequests.find((item) => item.id === detailPage.requestID);
      if (request && sources.some((source) => source.id === request.git_source_id)) {
        setSelectedSourceID(request.git_source_id);
      }
    }
  }, [deploymentRequests, detailPage, sources]);

  useEffect(() => {
    const appKey = selectedApp?.app_key || (selectedSource ? "" : selectedAppKey);
    if (!appKey) {
      setAppDetail(null);
      setHistory([]);
      setSourceFiles({});
      return;
    }
    let canceled = false;
    async function loadApp() {
      try {
        const [detail, nextHistory, source] = await Promise.all([
          api.app(appKey),
          api.appHistory(appKey),
          api.appSource(appKey).catch(() => ({ files: {} })),
        ]);
        if (canceled) return;
        setAppDetail(detail);
        setHistory(nextHistory);
        setSourceFiles(source.files || {});
      } catch (error) {
        if (!canceled) setNotice({ tone: "error", text: error instanceof Error ? error.message : String(error) });
      }
    }
    void loadApp();
    return () => {
      canceled = true;
    };
  }, [api, selectedApp?.app_key, selectedAppKey]);

  async function run(label: string, action: () => Promise<string | void>) {
    setBusy(true);
    setNotice({ tone: "info", text: label });
    try {
      const success = await action();
      setNotice({ tone: "ok", text: success || "Done" });
    } catch (error) {
      setNotice({ tone: "error", text: error instanceof Error ? error.message : String(error) });
    } finally {
      setBusy(false);
    }
  }

  function navigate(section: ConsoleSection) {
    setDetailPage(null);
    writeDetailPageToHistory(null);
    setActiveSection(section);
    if (section === "sources") setDetailTab("source");
    if (section === "releases") setDetailTab("contract");
    if (section === "audit") setDetailTab("history");
  }

  function openSettingsPage() {
    navigate("settings");
  }

  function saveSettings(nextSettings: ApiSettings) {
    setSettings(nextSettings);
    setNotice({ tone: "ok", text: "Settings saved." });
  }

  function openFCodeDetail(sourceID: number) {
    const next = { kind: "fcode", sourceID } satisfies DetailPage;
    setActiveSection("deployments");
    setSelectedSourceID(sourceID);
    setDetailPage(next);
    writeDetailPageToHistory(next);
  }

  function openRequestDetail(requestID: string) {
    const next = { kind: "request", requestID } satisfies DetailPage;
    const request = deploymentRequests.find((item) => item.id === requestID);
    if (request) setSelectedSourceID(request.git_source_id);
    setActiveSection("deployments");
    setDetailPage(next);
    writeDetailPageToHistory(next);
  }

  function closeDetailPage() {
    setDetailPage(null);
    writeDetailPageToHistory(null);
  }

  async function createDeploymentRequest(message: string) {
    if (!requestSource) return;
    setDeployError("");
    await run(`Creating deployment request for ${requestSource.name}`, async () => {
      const created = await api.createDeploymentRequest(requestSource.id, message ? { message } : {});
      setRequestSource(null);
      setSelectedSourceID(requestSource.id);
      await refresh();
      return `Requested ${created.source_name} at ${shortID(created.target_commit, 12)}.`;
    });
  }

  async function deployDeploymentRequest(message: string) {
    if (!reviewRequest) return;
    setDeployError("");
    await run(`Deploying request ${reviewRequest.id}`, async () => {
      const result = await api.deployDeploymentRequest(reviewRequest.id, message ? { confirm: true, message } : { confirm: true });
      setReviewRequest(null);
      setSelectedSourceID(result.request.git_source_id);
      setSelectedAppKey(result.sync_result.app);
      setDetailTab("history");
      setDetailPage({ kind: "request", requestID: reviewRequest.id });
      writeDetailPageToHistory({ kind: "request", requestID: reviewRequest.id });
      await refresh();
      return `Deployed ${result.sync_result.app} at ${shortID(result.sync_result.commit, 12)}.`;
    });
  }

  async function rejectDeploymentRequest(message: string) {
    if (!reviewRequest) return;
    setDeployError("");
    await run(`Rejecting request ${reviewRequest.id}`, async () => {
      const result = await api.rejectDeploymentRequest(reviewRequest.id, message ? { message } : {});
      setReviewRequest(null);
      setSelectedSourceID(result.git_source_id);
      setDetailPage({ kind: "request", requestID: result.id });
      writeDetailPageToHistory({ kind: "request", requestID: result.id });
      await refresh();
      return `Rejected deployment request for ${result.source_name}.`;
    });
  }

  const removeSource = (source: GitSource) => run(`Removing ${source.name}`, async () => {
    const confirmed = globalThis.confirm(`Remove source ${source.name}? This does not remove deployed history.`);
    if (!confirmed) return "Remove canceled.";
    await api.deleteGitSource(source.id);
    await refresh();
    return `Removed ${source.name}.`;
  });

  const topbarCopy = detailPage ? detailCopy(detailPage, sources, deploymentRequests) : sectionCopy[activeSection];

  return (
    <main className={sidebarCollapsed ? "appShell sidebarCollapsed" : "appShell"}>
      <Sidebar
        active={activeSection}
        collapsed={sidebarCollapsed}
        sourceCount={sources.length}
        appCount={apps.length}
        credentialCount={credentialCount}
        liveWorkers={liveWorkers}
        onNavigate={navigate}
        onToggleCollapsed={() => setSidebarCollapsed((current) => !current)}
      />
      <section className="mainArea">
        <Topbar
          title={topbarCopy.title}
          subtitle={topbarCopy.subtitle}
        />

        <div className="content">
          {notice.text && notice.tone === "error" ? <div id="notice" className={`notice ${notice.tone}`}>{notice.text}</div> : null}
          {activeSection === "settings" && !detailPage ? (
            <SettingsPage
              settings={settings}
              sourceCount={sources.length}
              appCount={apps.length}
              credentialCount={credentialCount}
              liveWorkers={liveWorkers}
              busy={busy}
              onSave={saveSettings}
              onRefresh={refresh}
            />
          ) : (
            <ActiveSection
              section={activeSection}
              sources={sources}
              apps={apps}
              selectedSourceID={selectedSourceID}
              selectedSource={selectedSource}
              selectedApp={selectedApp}
              detail={appDetail}
              history={history}
              sourceFiles={sourceFiles}
              search={search}
              activeTab={detailTab}
              actor={settings.actor}
              liveWorkers={liveWorkers}
              deploymentRequests={deploymentRequests}
              detailPage={detailPage}
              onSearch={setSearch}
              onSelectSource={setSelectedSourceID}
              onRegister={() => setRegistrationOpen(true)}
              onRequestDeploy={setRequestSource}
              onReviewRequest={setReviewRequest}
              onOpenFCodeDetail={openFCodeDetail}
              onOpenRequestDetail={openRequestDetail}
              onBackToList={closeDetailPage}
              onRemove={removeSource}
              onTabChange={setDetailTab}
              onSettings={openSettingsPage}
            />
          )}
        </div>
      </section>

      {notice.text && notice.tone !== "error" ? <div id="toast" className={`toast ${notice.tone}`}>{notice.text}</div> : null}

      {registrationOpen ? (
        <div id="registerSourceDialog" className="modalBackdrop" role="presentation">
          <section className="dialog wideDialog" aria-label="Register FCode source">
            <SourceRegistrationForm
              busy={busy}
              onCancel={() => setRegistrationOpen(false)}
              onRegister={(payload) => run("Registering source", async () => {
                const created = await api.registerGitSource(payload);
                setSelectedSourceID(created.id);
                setRegistrationOpen(false);
                await refresh();
                return `Registered ${created.name}.`;
              })}
              onProbe={(payload) => run("Probing repository", async () => {
                const result = await api.probeGitSource(payload);
                return result.reachable ? "Repository reachable for deployment." : result.error || "Repository is not reachable.";
              })}
              onCreateSample={() => run("Creating sample", async () => {
                await api.sample("echo");
                setRegistrationOpen(false);
                await refresh();
                return "Created sample source.";
              })}
            />
          </section>
        </div>
      ) : null}

      <RequestDeploymentDialog
        source={requestSource}
        actor={settings.actor}
        busy={busy}
        error={deployError}
        onClose={() => {
          setDeployError("");
          setRequestSource(null);
        }}
        onRequest={createDeploymentRequest}
        onOpenSettings={openSettingsPage}
      />

      <ReviewDeploymentRequestDialog
        request={reviewRequest}
        source={reviewRequest ? sources.find((source) => source.id === reviewRequest.git_source_id) || null : null}
        actor={settings.actor}
        busy={busy}
        error={deployError}
        onClose={() => {
          setDeployError("");
          setReviewRequest(null);
        }}
        onDeploy={deployDeploymentRequest}
        onReject={rejectDeploymentRequest}
        onOpenSettings={openSettingsPage}
      />
    </main>
  );
}

type ActiveSectionProps = ComponentProps<typeof DeploymentsSection> & {
  section: ConsoleSection;
};

function ActiveSection({ section, ...props }: ActiveSectionProps) {
  if (props.detailPage?.kind === "fcode") return <FCodeDetailSection {...props} detailPage={props.detailPage} />;
  if (props.detailPage?.kind === "request") return <DeploymentRequestDetailSection {...props} detailPage={props.detailPage} />;
  if (section === "sources") return <SourcesSection {...props} />;
  if (section === "releases") return <ReleasesSection {...props} />;
  if (section === "audit") return <AuditSection {...props} />;
  return <DeploymentsSection {...props} />;
}

function readDetailPageFromLocation(): DetailPage | null {
  if (typeof window === "undefined") return null;
  const params = new URLSearchParams(window.location.search);
  const detail = params.get("detail");
  if (detail === "fcode") {
    const sourceID = Number(params.get("source"));
    if (Number.isFinite(sourceID) && sourceID > 0) return { kind: "fcode", sourceID };
  }
  if (detail === "request") {
    const requestID = params.get("id");
    if (requestID) return { kind: "request", requestID };
  }
  return null;
}

function writeDetailPageToHistory(detailPage: DetailPage | null) {
  if (typeof window === "undefined") return;
  const url = new URL(window.location.href);
  url.searchParams.delete("detail");
  url.searchParams.delete("source");
  url.searchParams.delete("id");
  if (detailPage?.kind === "fcode") {
    url.searchParams.set("detail", "fcode");
    url.searchParams.set("source", String(detailPage.sourceID));
  }
  if (detailPage?.kind === "request") {
    url.searchParams.set("detail", "request");
    url.searchParams.set("id", detailPage.requestID);
  }
  window.history.pushState(null, "", `${url.pathname}${url.search}${url.hash}`);
}

function detailCopy(detailPage: DetailPage, sources: GitSource[], deploymentRequests: DeploymentRequest[]) {
  if (detailPage.kind === "fcode") {
    const source = sources.find((item) => item.id === detailPage.sourceID);
    const state = source?.last_synced_commit ? "deployed" : "registered";
    return {
      title: source ? `FCode / ${source.name} / ${state}` : "FCode Detail",
      subtitle: "Inspect source registration, active contract, deployment readiness, and audit evidence.",
    };
  }
  const request = deploymentRequests.find((item) => item.id === detailPage.requestID);
  return {
    title: request ? `Deployment Request / ${request.source_name} / ${request.status}` : "Deployment Request",
    subtitle: "Review the request timeline, pinned commit, operator decision, and deployment evidence.",
  };
}
